import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import '@/style/globals.css';
import Navbar from '@/components/layout/Navbar';
import Footer from '@/components/layout/Footer';
import { ThemeProvider } from '@/lib/theme-provider';
import { SessionProvider } from 'next-auth/react';
import Provider from '@/trpc/Provider';
import { Toaster } from '@/components/ui/sonner';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh-hk" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Provider>
          <ThemeProvider>
            <SessionProvider>
              <Navbar />
              <div className="flex min-h-screen items-center justify-center font-san">
                <main className="min-h-screen w-full">{children}</main>
              </div>
              <Toaster />
              <Footer />
            </SessionProvider>
          </ThemeProvider>
        </Provider>
      </body>
    </html>
  );
}
